// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Prodex.Data.Configurations;
using Prodex.Data.Models;
using System;
using System.Collections.Generic;
#nullable disable

namespace Prodex.Data;

public partial class DataContext : DbContext
{
    public DataContext(DbContextOptions<DataContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Dictionary> Dictionaries { get; set; }

    public virtual DbSet<DictionaryTerm> DictionaryTerms { get; set; }

    public virtual DbSet<History> Histories { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductTarget> ProductTargets { get; set; }

    public virtual DbSet<ProductTemplate> ProductTemplates { get; set; }

    public virtual DbSet<PtStatus> PtStatuses { get; set; }

    public virtual DbSet<SendTaskConfig> SendTaskConfigs { get; set; }

    public virtual DbSet<ServiceTaskConfig> ServiceTaskConfigs { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
            modelBuilder.ApplyConfiguration(new Configurations.DictionaryConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.DictionaryTermConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.HistoryConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ProductConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ProductTargetConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ProductTemplateConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PtStatusConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.SendTaskConfigConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ServiceTaskConfigConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UserConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
