// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Prodex.Data;
using Prodex.Data.Models;
using System;
using System.Collections.Generic;

namespace Prodex.Data.Configurations
{
    public partial class DictionaryConfiguration : IEntityTypeConfiguration<Dictionary>
    {
        public void Configure(EntityTypeBuilder<Dictionary> entity)
        {
            entity.Property(e => e.DateCreatedUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.DateUpdatedUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
            .IsRequired()
            .HasMaxLength(60);

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.DictionaryCreatedByNavigations)
            .HasForeignKey(d => d.CreatedBy)
            .HasConstraintName("FK_Dictionaries_CreatedBy_Users_Id");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.DictionaryUpdatedByNavigations)
            .HasForeignKey(d => d.UpdatedBy)
            .HasConstraintName("FK_Dictionaries_UpdatedBy_Users_Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Dictionary> entity);
    }
}
