// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Prodex.Data;
using Prodex.Data.Models;
using System;
using System.Collections.Generic;

namespace Prodex.Data.Configurations
{
    public partial class FieldConfigConfiguration : IEntityTypeConfiguration<FieldConfig>
    {
        public void Configure(EntityTypeBuilder<FieldConfig> entity)
        {
            entity.Property(e => e.DisplayName)
            .IsRequired()
            .HasMaxLength(50);

            entity.HasOne(d => d.Dictionary).WithMany(p => p.FieldConfigs)
            .HasForeignKey(d => d.DictionaryId)
            .HasConstraintName("FK_FieldConfigs_DictionaryId_Dictionaries_Id");

            entity.HasOne(d => d.Template).WithMany(p => p.FieldConfigs)
            .HasForeignKey(d => d.TemplateId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_FieldConfigs_TemplateId_ProductTemplates_Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FieldConfig> entity);
    }
}
