// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Prodex.Data;
using Prodex.Data.Models;
using System;
using System.Collections.Generic;

namespace Prodex.Data.Configurations
{
    public partial class ProductConfiguration : IEntityTypeConfiguration<Product>
    {
        public void Configure(EntityTypeBuilder<Product> entity)
        {
            entity.Property(e => e.CurrentStepId).HasDefaultValueSql("((1))");
            entity.Property(e => e.Name)
            .IsRequired()
            .HasMaxLength(60);

            entity.HasOne(d => d.Status).WithMany(p => p.Products)
            .HasForeignKey(d => d.StatusId)
            .HasConstraintName("FK_Products_StatusId_PtStatuses_Id");

            entity.HasOne(d => d.Template).WithMany(p => p.Products)
            .HasForeignKey(d => d.TemplateId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Products_TemplateId_ProductTemplates_Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Product> entity);
    }
}
