// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Prodex.Data;
using Prodex.Data.Models;
using System;
using System.Collections.Generic;

namespace Prodex.Data.Configurations
{
    public partial class ProductTemplateConfiguration : IEntityTypeConfiguration<ProductTemplate>
    {
        public void Configure(EntityTypeBuilder<ProductTemplate> entity)
        {
            entity.Property(e => e.Name)
            .IsRequired()
            .HasMaxLength(60);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductTemplate> entity);
    }
}
