// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Prodex.Data;
using Prodex.Data.Models;
using System;
using System.Collections.Generic;

namespace Prodex.Data.Configurations
{
    public partial class PtStatusConfiguration : IEntityTypeConfiguration<PtStatus>
    {
        public void Configure(EntityTypeBuilder<PtStatus> entity)
        {
            entity.Property(e => e.Color)
            .IsRequired()
            .HasMaxLength(60);
            entity.Property(e => e.DateCreatedUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.DateUpdatedUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Name)
            .IsRequired()
            .HasMaxLength(60);

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.PtStatusCreatedByNavigations)
            .HasForeignKey(d => d.CreatedBy)
            .HasConstraintName("FK_PtStatuses_CreatedBy_Users_Id");

            entity.HasOne(d => d.Template).WithMany(p => p.PtStatuses)
            .HasForeignKey(d => d.TemplateId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_PtStatuses_TemplateId_ProductTemplates_Id");

            entity.HasOne(d => d.UpdatedByNavigation).WithMany(p => p.PtStatusUpdatedByNavigations)
            .HasForeignKey(d => d.UpdatedBy)
            .HasConstraintName("FK_PtStatuses_UpdatedBy_Users_Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PtStatus> entity);
    }
}
