// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Prodex.Data;
using Prodex.Data.Models;
using System;
using System.Collections.Generic;

namespace Prodex.Data.Configurations
{
    public partial class SendTaskConfigConfiguration : IEntityTypeConfiguration<SendTaskConfig>
    {
        public void Configure(EntityTypeBuilder<SendTaskConfig> entity)
        {
            entity.HasIndex(e => e.StepId, "IX_SendTaskConfigs_StepId").IsUnique();

            entity.Property(e => e.StepId)
            .IsRequired()
            .HasMaxLength(20);

            entity.HasOne(d => d.Template).WithMany(p => p.SendTaskConfigs)
            .HasForeignKey(d => d.TemplateId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_SendTaskConfigs_TemplateId_ProductTemplates_Id");

            entity.HasOne(d => d.User).WithMany(p => p.SendTaskConfigs)
            .HasForeignKey(d => d.UserId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_SendTaskConfigs_UserId_Users_Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SendTaskConfig> entity);
    }
}
