// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Prodex.Data;
using Prodex.Data.Models;
using System;
using System.Collections.Generic;

namespace Prodex.Data.Configurations
{
    public partial class SequenceFlowConfigConfiguration : IEntityTypeConfiguration<SequenceFlowConfig>
    {
        public void Configure(EntityTypeBuilder<SequenceFlowConfig> entity)
        {
            entity.HasIndex(e => e.FlowId, "IX_SequenceFlowConfigs_FlowId").IsUnique();

            entity.Property(e => e.FlowId)
            .IsRequired()
            .HasMaxLength(20);
            entity.Property(e => e.LdynamicField).HasColumnName("LDynamicField");
            entity.Property(e => e.Lvalue)
            .HasMaxLength(1024)
            .HasColumnName("LValue");
            entity.Property(e => e.RdynamicField).HasColumnName("RDynamicField");
            entity.Property(e => e.Rvalue)
            .HasMaxLength(1024)
            .HasColumnName("RValue");

            entity.HasOne(d => d.LdynamicFieldNavigation).WithMany(p => p.SequenceFlowConfigLdynamicFieldNavigations)
            .HasForeignKey(d => d.LdynamicField)
            .HasConstraintName("FK_SequenceFlowConfigs_LDynamicField_FieldConfigs_Id");

            entity.HasOne(d => d.RdynamicFieldNavigation).WithMany(p => p.SequenceFlowConfigRdynamicFieldNavigations)
            .HasForeignKey(d => d.RdynamicField)
            .HasConstraintName("FK_SequenceFlowConfigs_RDynamicField_FieldConfigs_Id");

            entity.HasOne(d => d.Template).WithMany(p => p.SequenceFlowConfigs)
            .HasForeignKey(d => d.TemplateId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_SequenceFlowConfigs_TemplateId_ProductTemplates_Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SequenceFlowConfig> entity);
    }
}
