// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Prodex.Data;
using Prodex.Data.Models;
using System;
using System.Collections.Generic;

namespace Prodex.Data.Configurations
{
    public partial class ServiceTaskConfigConfiguration : IEntityTypeConfiguration<ServiceTaskConfig>
    {
        public void Configure(EntityTypeBuilder<ServiceTaskConfig> entity)
        {
            entity.HasIndex(e => e.StepId, "IX_ServiceTaskConfigs_StepId").IsUnique();

            entity.Property(e => e.ConfigJson)
            .IsRequired()
            .HasMaxLength(2048);
            entity.Property(e => e.StepId)
            .IsRequired()
            .HasMaxLength(20);

            entity.HasOne(d => d.Template).WithMany(p => p.ServiceTaskConfigs)
            .HasForeignKey(d => d.TemplateId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_ServiceTaskConfigs_TemplateId_ProductTemplates_Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ServiceTaskConfig> entity);
    }
}
