// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Prodex.Data.Models;

public partial class Dictionary
{
    public long Id { get; set; }

    public string Name { get; set; }

    public long? CreatedBy { get; set; }

    public long? UpdatedBy { get; set; }

    public DateTime DateCreatedUtc { get; set; }

    public DateTime DateUpdatedUtc { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<DictionaryTerm> DictionaryTerms { get; } = new List<DictionaryTerm>();

    public virtual ICollection<FieldConfig> FieldConfigs { get; } = new List<FieldConfig>();

    public virtual User UpdatedByNavigation { get; set; }
}