// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Prodex.Data.Models;

public partial class DynamicFieldValue
{
    public long Id { get; set; }

    public long FieldConfigId { get; set; }

    public long ProductId { get; set; }

    public string Value { get; set; }

    public long? CreatedBy { get; set; }

    public long? UpdatedBy { get; set; }

    public DateTime DateCreatedUtc { get; set; }

    public DateTime DateUpdatedUtc { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual FieldConfig FieldConfig { get; set; }

    public virtual Product Product { get; set; }

    public virtual User UpdatedByNavigation { get; set; }
}