// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Prodex.Data.Models;

public partial class FieldConfig
{
    public long Id { get; set; }

    public long TemplateId { get; set; }

    public string DisplayName { get; set; }

    public int Type { get; set; }

    public long? DictionaryId { get; set; }

    public virtual Dictionary Dictionary { get; set; }

    public virtual ICollection<DynamicFieldValue> DynamicFieldValues { get; } = new List<DynamicFieldValue>();

    public virtual ICollection<SequenceFlowConfig> SequenceFlowConfigLdynamicFieldNavigations { get; } = new List<SequenceFlowConfig>();

    public virtual ICollection<SequenceFlowConfig> SequenceFlowConfigRdynamicFieldNavigations { get; } = new List<SequenceFlowConfig>();

    public virtual ProductTemplate Template { get; set; }
}