// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Prodex.Data.Models;

public partial class SendTaskConfig
{
    public long Id { get; set; }

    public long TemplateId { get; set; }

    public string StepId { get; set; }

    public int TargetType { get; set; }

    public long UserId { get; set; }

    public virtual ProductTemplate Template { get; set; }

    public virtual User User { get; set; }
}