// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Prodex.Data.Models;

public partial class SequenceFlowConfig
{
    public long Id { get; set; }

    public long TemplateId { get; set; }

    public string FlowId { get; set; }

    public long? LdynamicField { get; set; }
    
    public long? LDictionaryTermId { get; set; }
    public long? RDictionaryTermId { get; set; }

    public string Lvalue { get; set; }

    public int OperatorType { get; set; }

    public long? RdynamicField { get; set; }

    public string Rvalue { get; set; }

    public virtual FieldConfig LdynamicFieldNavigation { get; set; }
    public virtual DictionaryTerm LDictionaryTerm { get; set; }
    public virtual DictionaryTerm RDictionaryTerm { get; set; }

    public virtual FieldConfig RdynamicFieldNavigation { get; set; }

    public virtual ProductTemplate Template { get; set; }
}