// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Prodex.Data.Models;

public partial class ServiceTaskConfig
{
    public long Id { get; set; }

    public long TemplateId { get; set; }

    public string StepId { get; set; }

    public int ActionType { get; set; }

    public string ConfigJson { get; set; }

    public long? CreatedBy { get; set; }

    public long? UpdatedBy { get; set; }

    public DateTime DateCreatedUtc { get; set; }

    public DateTime DateUpdatedUtc { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual ProductTemplate Template { get; set; }

    public virtual User UpdatedByNavigation { get; set; }
}