// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Prodex.Data.Interfaces;
using System;
using System.Collections.Generic;

namespace Prodex.Data.Models;

public partial class Product : IEntity
{
}