// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using Prodex.Client.Extensions;
using System.Net;
using System.Net.Http.Json;

namespace Prodex.Client.RestClients;


[Prodex.Client.DiHelpers.RegisterScoped]
public class AuthClient
{
    private readonly HttpClient client;

    public AuthClient(HttpClient client)
    {
        this.client = client;
    }
    
    public async System.Threading.Tasks.Task<Prodex.Client.RestClients.HttpResponseMessage<Prodex.Shared.Models.Auth.TokenModel>> Post(Prodex.Shared.Models.Auth.LoginModel model)
    {
        if (model.Validate(null).HasErrors)
            return new Prodex.Client.RestClients.HttpResponseMessage<Prodex.Shared.Models.Auth.TokenModel>(System.Net.HttpStatusCode.BadRequest);
        
        var result = new Prodex.Client.RestClients.HttpResponseMessage<Prodex.Shared.Models.Auth.TokenModel>(await client.PostAsJsonAsync("api/auth/login", model));

        await result.InitResultAsync();

        if (result.StatusCode == HttpStatusCode.BadRequest)
        {
            model.WithErrors(await result.Content.ReadAsStringAsync());
        }

        return result;
    }
}
