// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using Prodex.Client.Extensions;
using System.Net;
using System.Net.Http.Json;

namespace Prodex.Client.RestClients;


[Prodex.Client.DiHelpers.RegisterScoped]
public class ProcessesClient
{
    private readonly HttpClient client;

    public ProcessesClient(HttpClient client)
    {
        this.client = client;
    }
    
    public async System.Threading.Tasks.Task<Prodex.Shared.Pagination.Pagination<Prodex.Shared.Models.Processes.ListItemModel>> Get(Prodex.Shared.Pagination.Pager pager, Prodex.Shared.Models.Processes.FilterModel model)
    {
        return await client.GetFromJsonAsync<Prodex.Shared.Pagination.Pagination<Prodex.Shared.Models.Processes.ListItemModel>>("api/processes/", TypeMerger.TypeMerger.Merge(pager, model));
    }
    
    public async System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> Post(Prodex.Shared.Models.Processes.FormModel model)
    {
        if (model.Validate(null).HasErrors)
            return new System.Net.Http.HttpResponseMessage(System.Net.HttpStatusCode.BadRequest);
        
        var result = await client.PostAsJsonAsync("api/processes/", model);

        if (result.StatusCode == HttpStatusCode.BadRequest)
        {
            model.WithErrors(await result.Content.ReadAsStringAsync());
        }

        return result;
    }
}
