// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using Prodex.Client.Extensions;
using System.Net.Http.Json;

namespace Prodex.Client.RestClients;

public class ProcessesClient
{
    private readonly HttpClient client;

    public ProcessesClient(HttpClient client)
    {
        this.client = client;
    }
    
    public async System.Threading.Tasks.Task<System.Collections.Generic.List<Prodex.Shared.Models.Processes.ListItemModel>> Get(Prodex.Shared.Models.Processes.FilterModel model)
    {
        return await client.GetFromJsonAsync<System.Collections.Generic.List<Prodex.Shared.Models.Processes.ListItemModel>>("api/processes/", model);
    }
    
    public async System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> Post(Prodex.Shared.Models.Processes.FormModel model)
    {
        return await client.PostAsJsonAsync("api/processes/", model);
    }
}
