// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using Prodex.Client.Extensions;
using System.Net;
using System.Net.Http.Json;

namespace Prodex.Client.RestClients;


[Prodex.Client.DiHelpers.RegisterScoped]
public class ProductsClient
{
    private readonly HttpClient client;

    public ProductsClient(HttpClient client)
    {
        this.client = client;
    }
    
    public async System.Threading.Tasks.Task<Prodex.Shared.Pagination.Pagination<Prodex.Shared.Models.Products.ListItemModel>> Get(Prodex.Shared.Pagination.Pager pager, Prodex.Shared.Models.Products.FilterModel model)
    {
        return await client.GetFromJsonAsync<Prodex.Shared.Pagination.Pagination<Prodex.Shared.Models.Products.ListItemModel>>("api/products/", TypeMerger.TypeMerger.Merge(pager, model));
    }
    
    public async System.Threading.Tasks.Task<Prodex.Client.RestClients.HttpResponseMessage<System.Object>> Post(Prodex.Shared.Models.Products.FormModel model)
    {
        if (model.Validate(null).HasErrors)
            return new Prodex.Client.RestClients.HttpResponseMessage<System.Object>(System.Net.HttpStatusCode.BadRequest);
        
        var result = new Prodex.Client.RestClients.HttpResponseMessage<System.Object>(await client.PostAsJsonAsync("api/products/", model));

        await result.InitResultAsync();

        if (result.StatusCode == HttpStatusCode.BadRequest)
        {
            model.WithErrors(await result.Content.ReadAsStringAsync());
        }

        return result;
    }
}
